# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: 1000+ theorems
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Keeping track of formalizations of theorems from the Wikipedia's List of theorems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://1000-plus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages

collections:
  thm:
    output: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

atom_feed:
  hide: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/1000-plus-theorems/1000-plus"

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
